name: Run Tests

on:
  - push
  - pull_request
      
permissions: {}

jobs:
  test:
    permissions:
      contents: read
      
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [stable, oldstable]
        
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go }}
          
      - name: Install dependencies
        run: go get ./...
        
      - name: Run tests
        run: go test ./...
